# Base image
FROM node:14-alpine

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar archivos de la aplicación
COPY frontend.js package.json /app/

# Instalar dependencias
RUN npm install --only=production

# Comando por defecto para ejecutar la aplicación
CMD ["node", "frontend.js"]
