# Usa la imagen oficial de Node.js.
FROM node:14

# Crea y cambia al directorio del contenedor.
WORKDIR /usr/src/app

# Copia los archivos de la aplicación.
COPY package*.json ./
COPY public ./public
COPY frontend.js ./

# Instala las dependencias de producción.
RUN npm install --only=production

# Expone el puerto en el que la aplicación se ejecutará.
EXPOSE 3000

# Ejecuta la aplicación.
CMD [ "node", "frontend.js" ]
