apiVersion: apps/v1
kind: Deployment
metadata:
  name: productos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productos
  template:
    metadata:
      labels:
        app: productos
    spec:
      containers:
      - name: productos
        image: 7brandon/productos
        ports:
        - containerPort: 3000