# Utiliza una imagen base de Node.js versión 14 para desarrollo
FROM node:14

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia el archivo package.json y package-lock.json (si existe)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

# Expone el puerto en el que la aplicación va a escuchar
EXPOSE 3000

# Comando para ejecutar la aplicación en modo desarrollo
CMD ["node", "cliente.js"]
