# Base image
FROM node:14-alpine

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar archivos de la aplicación
COPY cliente.js package.json /app/

# Instalar dependencias
RUN npm install

# Comando por defecto para ejecutar la aplicación
CMD ["node", "cliente.js"]
